fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: https://github.com/ripienaar/puppet-concat.git
    kwalify: https://github.com/puppetlabs/puppetlabs-kwalify.git
  symlinks:
    pgbouncer: "#{source_dir}"
